export const REQUEST_SONG_LIST = 'REQUEST_SONG_LIST';
export const RECEIVE_SONG_LIST = 'RECEIVE_SONG_LIST';
export const ERROR_RECEIVE_SONG_LIST = 'ERROR_RECEIVE_SONG_LIST';
export const REQUEST_DELETE_SONG = 'REQUEST_DELETE_SONG';
export const SUCCESS_DELETE_SONG = 'SUCCESS_DELETE_SONG';
export const ERROR_DELETE_SONG = 'ERROR_DELETE_SONG';
export const ADD_SONG = 'ADD_SONG'
export const ERROR_ADD_SONG = 'ERROR_ADD_SONG'