export const ERROR_RECEIVE_SONG = 'ERROR_RECEIVE_SONG';
export const REQUEST_SONG = 'REQUEST_SONG';
export const RECEIVE_SONG = 'RECEIVE_SONG';
export const UPDATE_SONG = 'UPDATE_SONG'
export const ERROR_UPDATE_SONG = 'ERROR_UPDATE_SONG'